algoritmo "soma e divisao"
// Função :
// Autor :
// Data : 06/06/2013
// Seção de Declarações 
var
  num1: Real
  num2: Real
  soma: Real
  divisao: Real
  
inicio
escreva ("entre com um número real: ")
leia (num1)
escreva ("entre com um segundo número real: ")
leia (num2)
soma <- num1+num2
divisao <- num1/num2
escreval ("A soma dos números é", soma)
escreval ("A divisão é", divisao)


fimalgoritmo

